#ifndef SERIAL_PROTOCOL
#define SERIAL_PROTOCOL

#define START_COMMAND "START\n"
#define END_COMMAND "END\n"

#define SPECS_COMMAND 's'
#define TRIGGER_COMMAND 't'
#define SIMU_TRIGGER_COMMAND 'S'
#define FORCE_TRIGGER_COMMAND 'f'
#define LOW_RANGE_COMMAND 'r'
#define HIGH_RANGE_COMMAND 'R'
#define TRIGGER_LEVEL_COMMAND 'l'
#define CLOCK_DIV_COMMAND 'c'

#endif
